spring:
  application:
    name: 'clinic'
  main:
    banner:
      mode: 'off'
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:E:/dev/clinic/clinic-db'
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
  mail:
    host: 'smtp.mailtrap.io'
    port: 2525
    username: '${MAIL_USERNAME}'
    password: '${MAIL_PASSWORD}'
    properties:
      smtp:
        auth: 'true'
        starttls:
          enable: 'true'
#Actuator
management:
  endpoints:
    web:
      base:
        path: '/status'
  metrics:
    enable:
      http: false
#Api for weather
weather:
  api:
    endpoint:
      prod: 'http://api.openweathermap.org/data/2.5/weather?q='
  app:
    token: '4af1c105dcf10a54eab54afc6edd20eb'
#admin email
admin:
  mail: 'pelemistrz@gmail.com'

